# Generated by Django 3.2 on 2021-05-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Photourl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CallBooked',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.TimeField()),
                ('Advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.advisor')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.users')),
            ],
        ),
    ]
